<?php
/**
 * @file
 * Code for the Video Hero Unit feature.
 */

include_once 'cu_video_hero_unit.features.inc';

/**
 * Implements hook_page_alter().
 *
 */

function cu_video_hero_unit_page_alter(&$page) {
  drupal_add_css(drupal_get_path('module','cu_video_hero_unit') . '/css/cu_video_hero_unit.css');
  drupal_add_js('//www.youtube.com/iframe_api', 'external');
}

/**
 * Implements hook_theme_registry_alter().
 *
 * Let Drupal know that we've got bean--video-hero-unit.tpl.php in our module directory.
 */
function cu_video_hero_unit_theme_registry_alter(&$theme_registry) {
  $module_path = drupal_get_path('module', 'cu_video_hero_unit');
  $theme_registry_copy = $theme_registry;
  _theme_process_registry($theme_registry_copy, 'phptemplate', 'theme_engine', 'bean', $module_path);
  $theme_registry += array_diff_key($theme_registry_copy, $theme_registry);
  $hooks = array('bean');
  foreach ($hooks as $h) {
	  if (isset($theme_registry[$h]['theme paths'])) {
	    $first_element = array_shift($theme_registry[$h]['theme paths']);
	    array_unshift($theme_registry[$h]['theme paths'], array_shift($theme_registry[$h]['theme paths']), $module_path);
  	}
  }
}

/**
 * Implements hook_preprocess_entity().
 *
 * Prepare render/tpl variables
 */
function cu_video_hero_unit_preprocess_entity(&$vars) {
  $entity_type = $vars['elements']['#entity_type'];
  $bundle = $vars['elements']['#bundle'];

  // Only preprocess hero unit beans.
  if ($entity_type == 'bean' && $bundle == 'video_hero_unit') {
    if (!empty($vars['content']['field_hero_unit_image'])) {
      $image = render($vars['content']['field_hero_unit_image']);
      $vars['image'] = trim(preg_replace('/\s+/', ' ', $image));

      // Render image for large displays
      $vars['content']['field_hero_unit_image'][0]['#image_style'] = 'hero';
      $image_large = render($vars['content']['field_hero_unit_image']);
      $vars['image_large'] = trim(preg_replace('/\s+/', ' ', $image_large));

      // Render image for medium displays
      $vars['content']['field_hero_unit_image'][0]['#image_style'] = 'large';
      $image_medium = render($vars['content']['field_hero_unit_image']);
      $vars['image_medium'] = trim(preg_replace('/\s+/', ' ', $image_medium));

      // Render image for small displays
      $vars['content']['field_hero_unit_image'][0]['#image_style'] = 'medium';
      $image_small = render($vars['content']['field_hero_unit_image']);
      $vars['image_small'] = trim(preg_replace('/\s+/', ' ', $image_small));
    }
    $vars['priority'] = isset($vars['content']['field_hero_unit_size_priority'][0]['#markup']) ? $vars['content']['field_hero_unit_size_priority'][0]['#markup'] : 'text';

    // Get bean ID so we can make a unique id
    $vars['bid'] = $vars['bean']->bid;

    // FUTURE FEATURE: Check to make sure video exists
    $vars['video_url'] = 'https://player.vimeo.com/video/' . $vars['content']['field_video_hero_url'][0]['#markup'];





    // Build array of classes
    $classes_array = array();
    $classes_array[] = 'hero-unit';
    $classes_array[] = 'hero-align-' . render($vars['content']['field_hero_unit_text_align'][0]['#markup']);
    $classes_array[] = 'hero-text-' . render($vars['content']['field_hero_unit_text_color'][0]['#markup']);
    $classes_array[] = 'hero-links-' . render($vars['content']['field_hero_unit_link_color'][0]['#markup']);
    $classes_array[] = 'hero-unit-text';
    $vars['hero_classes'] = join(' ', $classes_array);

  }
}

function cu_video_hero_unit_form_bean_form_alter(&$form, &$form_state, $form_id) {
  //dpm($form);
  if ($form['bean']['#value']->type == 'video_hero_unit') {



  }
}


/*
 * Implements hook_secure_permissions
 *
 * Adding permissions for video hero unit bean
 */
function cu_video_hero_unit_secure_permissions($role) {
  $permissions = array(
    'anonymous user' => array(
      'view any video_hero_unit bean',
    ),
    'authenticated user' => array(
      'view any video_hero_unit bean',
    ),
    'administrator' => array(
      'create any video_hero_unit bean',
      'delete any video_hero_unit bean',
      'edit any video_hero_unit bean',
      'view any video_hero_unit bean',
    ),
    'content_editor' => array(
      'create any video_hero_unit bean',
      'delete any video_hero_unit bean',
      'edit any video_hero_unit bean',
      'view any video_hero_unit bean',
    ),
    'developer' => array(
      'create any video_hero_unit bean',
      'delete any video_hero_unit bean',
      'edit any video_hero_unit bean',
      'view any video_hero_unit bean',
    ),
    'site_owner' => array(
      'create any video_hero_unit bean',
      'delete any video_hero_unit bean',
      'edit any video_hero_unit bean',
      'view any video_hero_unit bean',
    ),
  );

  if (isset($permissions[$role])) {
    return $permissions[$role];
  }
}
